title: Abhilashini A J
description: "Human-centered System Design"
baseurl: /
url: "https://abhilashini.github.io"
markdown: kramdown
collections:
  articles:
    output: true
    permalink: /articles/:name/